name: 'test my project'
on:
  push:
    branches:
      - master
jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '13.x'

      #- name: 'set ssh'
      #  run: set -eu && mkdir "$HOME/.ssh" && echo "${{ secrets.key }}" > "$HOME/.ssh/key" && chmod 600 "$HOME/.ssh/key"

      - name: 'install'
        run: npm i

      - name: 'build'
        run: npm run build



      - name: 'cd'
        run: cd app

      - name: 'git1'
        run: git config --global user.email "ferym26@gmail.com" && git config --global user.name "ferym26"

      - name: 'git2'
        run: git status
      - name: 'git3'
        run: git add .
      - name: 'git4'
        run: git commit -m 'auto'
      - name: 'git5'
        run: git push -u origin build
